#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Console\TimeCommand;

$app = new Application;
$app -> add(new TimeCommand());
$app->setDefaultCommand('hit', true);
$app -> run();
